// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

// Defines values for MailAccountState.
const (
	Active    MailAccountState = "active"
	Suspended MailAccountState = "suspended"
)

// Valid indicates whether the value is a known member of the MailAccountState enum.
func (e MailAccountState) Valid() bool {
	switch e {
	case Active:
		return true
	case Suspended:
		return true
	default:
		return false
	}
}

// Defines values for MailboxResponseDtoType.
const (
	MailboxResponseDtoTypeArchive MailboxResponseDtoType = "archive"
	MailboxResponseDtoTypeDrafts  MailboxResponseDtoType = "drafts"
	MailboxResponseDtoTypeInbox   MailboxResponseDtoType = "inbox"
	MailboxResponseDtoTypeSent    MailboxResponseDtoType = "sent"
	MailboxResponseDtoTypeSpam    MailboxResponseDtoType = "spam"
	MailboxResponseDtoTypeTrash   MailboxResponseDtoType = "trash"
)

// Valid indicates whether the value is a known member of the MailboxResponseDtoType enum.
func (e MailboxResponseDtoType) Valid() bool {
	switch e {
	case MailboxResponseDtoTypeArchive:
		return true
	case MailboxResponseDtoTypeDrafts:
		return true
	case MailboxResponseDtoTypeInbox:
		return true
	case MailboxResponseDtoTypeSent:
		return true
	case MailboxResponseDtoTypeSpam:
		return true
	case MailboxResponseDtoTypeTrash:
		return true
	default:
		return false
	}
}

// Defines values for ReplyEmailRequestDtoDeliveryMode.
const (
	ReplyEmailRequestDtoDeliveryModeEXTERNAL ReplyEmailRequestDtoDeliveryMode = "EXTERNAL"
	ReplyEmailRequestDtoDeliveryModeINTERNXT ReplyEmailRequestDtoDeliveryMode = "INTERNXT"
)

// Valid indicates whether the value is a known member of the ReplyEmailRequestDtoDeliveryMode enum.
func (e ReplyEmailRequestDtoDeliveryMode) Valid() bool {
	switch e {
	case ReplyEmailRequestDtoDeliveryModeEXTERNAL:
		return true
	case ReplyEmailRequestDtoDeliveryModeINTERNXT:
		return true
	default:
		return false
	}
}

// Defines values for SendEmailRequestDtoDeliveryMode.
const (
	SendEmailRequestDtoDeliveryModeEXTERNAL SendEmailRequestDtoDeliveryMode = "EXTERNAL"
	SendEmailRequestDtoDeliveryModeINTERNXT SendEmailRequestDtoDeliveryMode = "INTERNXT"
)

// Valid indicates whether the value is a known member of the SendEmailRequestDtoDeliveryMode enum.
func (e SendEmailRequestDtoDeliveryMode) Valid() bool {
	switch e {
	case SendEmailRequestDtoDeliveryModeEXTERNAL:
		return true
	case SendEmailRequestDtoDeliveryModeINTERNXT:
		return true
	default:
		return false
	}
}

// Defines values for UpdateEmailRequestDtoMailbox.
const (
	UpdateEmailRequestDtoMailboxArchive UpdateEmailRequestDtoMailbox = "archive"
	UpdateEmailRequestDtoMailboxDrafts  UpdateEmailRequestDtoMailbox = "drafts"
	UpdateEmailRequestDtoMailboxInbox   UpdateEmailRequestDtoMailbox = "inbox"
	UpdateEmailRequestDtoMailboxSent    UpdateEmailRequestDtoMailbox = "sent"
	UpdateEmailRequestDtoMailboxSpam    UpdateEmailRequestDtoMailbox = "spam"
	UpdateEmailRequestDtoMailboxTrash   UpdateEmailRequestDtoMailbox = "trash"
)

// Valid indicates whether the value is a known member of the UpdateEmailRequestDtoMailbox enum.
func (e UpdateEmailRequestDtoMailbox) Valid() bool {
	switch e {
	case UpdateEmailRequestDtoMailboxArchive:
		return true
	case UpdateEmailRequestDtoMailboxDrafts:
		return true
	case UpdateEmailRequestDtoMailboxInbox:
		return true
	case UpdateEmailRequestDtoMailboxSent:
		return true
	case UpdateEmailRequestDtoMailboxSpam:
		return true
	case UpdateEmailRequestDtoMailboxTrash:
		return true
	default:
		return false
	}
}

// Defines values for EmailControllerListParamsMailbox.
const (
	EmailControllerListParamsMailboxArchive EmailControllerListParamsMailbox = "archive"
	EmailControllerListParamsMailboxDrafts  EmailControllerListParamsMailbox = "drafts"
	EmailControllerListParamsMailboxInbox   EmailControllerListParamsMailbox = "inbox"
	EmailControllerListParamsMailboxSent    EmailControllerListParamsMailbox = "sent"
	EmailControllerListParamsMailboxSpam    EmailControllerListParamsMailbox = "spam"
	EmailControllerListParamsMailboxTrash   EmailControllerListParamsMailbox = "trash"
)

// Valid indicates whether the value is a known member of the EmailControllerListParamsMailbox enum.
func (e EmailControllerListParamsMailbox) Valid() bool {
	switch e {
	case EmailControllerListParamsMailboxArchive:
		return true
	case EmailControllerListParamsMailboxDrafts:
		return true
	case EmailControllerListParamsMailboxInbox:
		return true
	case EmailControllerListParamsMailboxSent:
		return true
	case EmailControllerListParamsMailboxSpam:
		return true
	case EmailControllerListParamsMailboxTrash:
		return true
	default:
		return false
	}
}

// AttachmentRefDto defines model for AttachmentRefDto.
type AttachmentRefDto struct {
	// BlobId Example: T1a2b3c…
	BlobId string `json:"blobId"`

	// Name Example: photo.jpg
	Name string `json:"name"`

	// Size Size in bytes
	//
	// Example: 4096
	Size float32 `json:"size"`

	// Type Example: image/jpeg
	Type string `json:"type"`
}

// CreateMailAccountDto defines model for CreateMailAccountDto.
type CreateMailAccountDto struct {
	// Address Example: alice
	Address string `json:"address"`

	// DisplayName Example: Alice Smith
	DisplayName string `json:"displayName"`

	// Domain Example: inxt.eu
	Domain string                  `json:"domain"`
	Keys   MailAddressKeyBundleDto `json:"keys"`
}

// CreateMailAccountResponseDto defines model for CreateMailAccountResponseDto.
type CreateMailAccountResponseDto struct {
	// Address Example: alice@inxt.eu
	Address string `json:"address"`

	// Domain Example: inxt.eu
	Domain string `json:"domain"`

	// Id Example: f3a1b2c4-1234-4abc-9def-0123456789ab
	Id string `json:"id"`
}

// DraftEmailRequestDto defines model for DraftEmailRequestDto.
type DraftEmailRequestDto struct {
	Attachments *[]AttachmentRefDto `json:"attachments,omitempty"`
	Bcc         *[]EmailAddressDto  `json:"bcc,omitempty"`
	Cc          *[]EmailAddressDto  `json:"cc,omitempty"`

	// Encryption When present, the draft body is stored encrypted. Only the sender can decrypt it later, so wrappedKeys should contain a single entry built from the sender's own public key.
	Encryption *EncryptionBlockDto `json:"encryption,omitempty"`

	// HtmlBody Example: <p>Still working on this…</p>
	HtmlBody *string `json:"htmlBody,omitempty"`

	// Subject Example: Draft: project update
	Subject *string `json:"subject,omitempty"`

	// TextBody Example: Still working on this…
	TextBody *string            `json:"textBody,omitempty"`
	To       *[]EmailAddressDto `json:"to,omitempty"`
}

// EmailAddressDto defines model for EmailAddressDto.
type EmailAddressDto struct {
	// Email Example: alice@internxt.me
	Email string `json:"email"`

	// Name Example: Alice Smith
	Name *string `json:"name,omitempty"`
}

// EmailAttachmentDto defines model for EmailAttachmentDto.
type EmailAttachmentDto struct {
	// BlobId Example: T1a2b3c…
	BlobId string `json:"blobId"`

	// Name Example: photo.jpg
	Name string `json:"name"`

	// Size Size in bytes
	//
	// Example: 4096
	Size float32 `json:"size"`

	// Type Example: image/jpeg
	Type string `json:"type"`
}

// EmailCreatedResponseDto defines model for EmailCreatedResponseDto.
type EmailCreatedResponseDto struct {
	// Id ID of the created email
	//
	// Example: Ma1f09b…
	Id string `json:"id"`
}

// EmailListResponseDto defines model for EmailListResponseDto.
type EmailListResponseDto struct {
	Emails []EmailSummaryResponseDto `json:"emails"`

	// HasMoreMails Whether there are more emails to fetch
	//
	// Example: true
	HasMoreMails bool `json:"hasMoreMails"`

	// NextAnchor Example: Ma1f09b…
	NextAnchor *string `json:"nextAnchor,omitempty"`

	// Total Total emails in the mailbox
	//
	// Example: 142
	Total float32 `json:"total"`
}

// EmailResponseDto defines model for EmailResponseDto.
type EmailResponseDto struct {
	Attachments []EmailAttachmentDto `json:"attachments"`
	Bcc         []EmailAddressDto    `json:"bcc"`
	Cc          []EmailAddressDto    `json:"cc"`

	// Encryption Present only for encrypted emails. Carries the encrypted preview and the de-identified wrapped keys for inline client-side decryption.
	Encryption *EncryptedSummaryDto `json:"encryption,omitempty"`
	From       []EmailAddressDto    `json:"from"`

	// HasAttachment Example: false
	HasAttachment bool `json:"hasAttachment"`

	// HtmlBody Example: <p>Hi team, here are the notes…</p>
	HtmlBody *string `json:"htmlBody"`

	// Id Example: Ma1f09b…
	Id string `json:"id"`

	// IsDraft Example: false
	IsDraft bool `json:"isDraft"`

	// IsFlagged Example: false
	IsFlagged bool `json:"isFlagged"`

	// IsRead Example: true
	IsRead bool `json:"isRead"`

	// LastReceivedAt receivedAt of the most recent email in the thread (cross-mailbox). Set only when the list collapses threads.
	//
	// Example: 2025-06-15T10:30:00Z
	LastReceivedAt *string `json:"lastReceivedAt,omitempty"`

	// MailboxIds Example: ["d","a"]
	MailboxIds []string `json:"mailboxIds"`

	// Participants Unique senders that have written in the thread (cross-mailbox), deduplicated by email. Set only when the list collapses threads.
	Participants *[]EmailAddressDto `json:"participants,omitempty"`

	// Preview Example: Hi team, here are the notes from…
	Preview string `json:"preview"`

	// ReceivedAt Example: 2025-06-15T10:30:00Z
	ReceivedAt string            `json:"receivedAt"`
	ReplyTo    []EmailAddressDto `json:"replyTo"`

	// SentAt Example: 2025-06-15T10:29:55Z
	SentAt *string `json:"sentAt"`

	// Size Size in bytes
	//
	// Example: 4096
	Size float32 `json:"size"`

	// Subject Example: Weekly sync notes
	Subject string `json:"subject"`

	// TextBody Example: Hi team, here are the notes…
	TextBody *string `json:"textBody"`

	// ThreadId Example: T1a2b3c…
	ThreadId string `json:"threadId"`

	// ThreadSize Total number of emails in the thread (cross-mailbox). Set only when the list collapses threads.
	//
	// Example: 3
	ThreadSize *float32          `json:"threadSize,omitempty"`
	To         []EmailAddressDto `json:"to"`
}

// EmailSummaryResponseDto defines model for EmailSummaryResponseDto.
type EmailSummaryResponseDto struct {
	// Encryption Present only for encrypted emails. Carries the encrypted preview and the de-identified wrapped keys for inline client-side decryption.
	Encryption *EncryptedSummaryDto `json:"encryption,omitempty"`
	From       []EmailAddressDto    `json:"from"`

	// HasAttachment Example: false
	HasAttachment bool `json:"hasAttachment"`

	// Id Example: Ma1f09b…
	Id string `json:"id"`

	// IsDraft Example: false
	IsDraft bool `json:"isDraft"`

	// IsFlagged Example: false
	IsFlagged bool `json:"isFlagged"`

	// IsRead Example: true
	IsRead bool `json:"isRead"`

	// LastReceivedAt receivedAt of the most recent email in the thread (cross-mailbox). Set only when the list collapses threads.
	//
	// Example: 2025-06-15T10:30:00Z
	LastReceivedAt *string `json:"lastReceivedAt,omitempty"`

	// MailboxIds Example: ["d","a"]
	MailboxIds []string `json:"mailboxIds"`

	// Participants Unique senders that have written in the thread (cross-mailbox), deduplicated by email. Set only when the list collapses threads.
	Participants *[]EmailAddressDto `json:"participants,omitempty"`

	// Preview Example: Hi team, here are the notes from…
	Preview string `json:"preview"`

	// ReceivedAt Example: 2025-06-15T10:30:00Z
	ReceivedAt string `json:"receivedAt"`

	// Size Size in bytes
	//
	// Example: 4096
	Size float32 `json:"size"`

	// Subject Example: Weekly sync notes
	Subject string `json:"subject"`

	// ThreadId Example: T1a2b3c…
	ThreadId string `json:"threadId"`

	// ThreadSize Total number of emails in the thread (cross-mailbox). Set only when the list collapses threads.
	//
	// Example: 3
	ThreadSize *float32          `json:"threadSize,omitempty"`
	To         []EmailAddressDto `json:"to"`
}

// EncryptedSummaryDto defines model for EncryptedSummaryDto.
type EncryptedSummaryDto struct {
	// EncryptedPreview Encrypted preview snippet (base64)
	EncryptedPreview string `json:"encryptedPreview"`

	// WrappedKeys Wrapped keys that unlock the preview, labeled per recipient; the caller picks theirs by address
	WrappedKeys []EncryptedWrappedKeyDto `json:"wrappedKeys"`
}

// EncryptedWrappedKeyDto defines model for EncryptedWrappedKeyDto.
type EncryptedWrappedKeyDto struct {
	// EncryptedForEmail Recipient address this key was wrapped for
	EncryptedForEmail string `json:"encryptedForEmail"`

	// EncryptedKey Encrypted symmetric key (base64)
	EncryptedKey string `json:"encryptedKey"`

	// HybridCiphertext Hybrid ciphertext (base64)
	HybridCiphertext string `json:"hybridCiphertext"`
}

// EncryptionBlockDto defines model for EncryptionBlockDto.
type EncryptionBlockDto struct {
	// EncryptedAttachmentsSessionKey Encrypted attachments session key (base64), same session key as the body
	EncryptedAttachmentsSessionKey string `json:"encryptedAttachmentsSessionKey"`

	// EncryptedPreview Encrypted preview snippet (base64), ~256 chars plaintext, same session key as the body
	EncryptedPreview string `json:"encryptedPreview"`

	// EncryptedText Encrypted body (base64)
	EncryptedText string `json:"encryptedText"`

	// Version Example: v3
	Version string `json:"version"`

	// WrappedKeys Wrapped session keys, labeled per recipient; one entry unlocks body, preview and attachments key
	WrappedKeys []EncryptedWrappedKeyDto `json:"wrappedKeys"`
}

// LookupRecipientKeysRequestDto defines model for LookupRecipientKeysRequestDto.
type LookupRecipientKeysRequestDto struct {
	// Addresses 1-50 email addresses to look up
	//
	// Example: ["alice@internxt.me","bob@internxt.com"]
	Addresses []string `json:"addresses"`
}

// LookupRecipientKeysResponseDto defines model for LookupRecipientKeysResponseDto.
type LookupRecipientKeysResponseDto struct {
	Recipients []RecipientKeyDto `json:"recipients"`
}

// MailAccountKeysResponseDto defines model for MailAccountKeysResponseDto.
type MailAccountKeysResponseDto struct {
	// Address Example: alice@inxt.eu
	Address string `json:"address"`

	// EncryptionPrivateKey Private key encrypted with the encryption keystore key (base64)
	EncryptionPrivateKey string `json:"encryptionPrivateKey"`

	// PublicKey Hybrid (X25519 + ML-KEM-768) public key, base64-encoded
	PublicKey string `json:"publicKey"`

	// RecoveryPrivateKey Private key encrypted with the recovery keystore key (base64)
	RecoveryPrivateKey string `json:"recoveryPrivateKey"`
}

// MailAccountState defines model for MailAccountState.
type MailAccountState string

// MailAccountStatusResponseDto defines model for MailAccountStatusResponseDto.
type MailAccountStatusResponseDto struct {
	// DefaultAddress Default address of the account, null if none is set
	//
	// Example: alice@inxt.eu
	DefaultAddress *string `json:"defaultAddress,omitempty"`

	// DeletionAt Scheduled deletion date for suspended accounts; null when active
	//
	// Example: 2026-05-31T10:29:55.000Z
	DeletionAt *string `json:"deletionAt,omitempty"`

	// Id Example: f3a1b2c4-1234-4abc-9def-0123456789ab
	Id string `json:"id"`

	// Status Example: active
	Status MailAccountState `json:"status"`

	// SuspendedAt When the account was suspended; null when active
	//
	// Example: 2026-05-01T10:29:55.000Z
	SuspendedAt *string `json:"suspendedAt,omitempty"`
}

// MailAddressKeyBundleDto defines model for MailAddressKeyBundleDto.
type MailAddressKeyBundleDto struct {
	// EncryptionPrivateKey Private key encrypted with the encryption keystore key (base64)
	EncryptionPrivateKey string `json:"encryptionPrivateKey"`

	// PublicKey Hybrid (X25519 + ML-KEM-768) public key, base64-encoded
	PublicKey string `json:"publicKey"`

	// RecoveryPrivateKey Private key encrypted with the recovery keystore key (base64)
	RecoveryPrivateKey string `json:"recoveryPrivateKey"`
}

// MailDomainDto defines model for MailDomainDto.
type MailDomainDto struct {
	// CreatedAt Example: 2025-06-15T10:29:55Z
	CreatedAt string `json:"createdAt"`

	// Domain Example: internxt.me
	Domain string `json:"domain"`

	// Id Example: f3a1b2c4-…
	Id string `json:"id"`

	// Status Example: active
	Status string `json:"status"`

	// UpdatedAt Example: 2025-06-15T10:29:55Z
	UpdatedAt string `json:"updatedAt"`
}

// MailboxResponseDto defines model for MailboxResponseDto.
type MailboxResponseDto struct {
	// Id Example: f3a1b2c4-…
	Id string `json:"id"`

	// Name Example: Inbox
	Name     string                  `json:"name"`
	ParentId *map[string]interface{} `json:"parentId"`

	// TotalEmails Example: 142
	TotalEmails float32 `json:"totalEmails"`

	// Type Example: inbox
	Type *MailboxResponseDtoType `json:"type"`

	// UnreadEmails Example: 3
	UnreadEmails float32 `json:"unreadEmails"`
}

// MailboxResponseDtoType Example: inbox
type MailboxResponseDtoType string

// RecipientKeyDto defines model for RecipientKeyDto.
type RecipientKeyDto struct {
	// Address Example: alice@internxt.me
	Address string `json:"address"`

	// PublicKey Example: base64encodedpublickey==
	PublicKey *string `json:"publicKey"`
}

// ReplyEmailRequestDto defines model for ReplyEmailRequestDto.
type ReplyEmailRequestDto struct {
	Attachments *[]AttachmentRefDto `json:"attachments,omitempty"`
	Bcc         *[]EmailAddressDto  `json:"bcc,omitempty"`
	Cc          *[]EmailAddressDto  `json:"cc,omitempty"`

	// DeliveryMode Example: INTERNXT
	DeliveryMode *ReplyEmailRequestDtoDeliveryMode `json:"deliveryMode,omitempty"`

	// DraftId JMAP id of the draft being sent. When present, the draft is destroyed after the email is sent so it no longer appears in the Drafts folder.
	//
	// Example: Ma1f09b…
	DraftId    *string             `json:"draftId,omitempty"`
	Encryption *EncryptionBlockDto `json:"encryption,omitempty"`

	// HtmlBody HTML version of the email body
	//
	// Example: <p>Hi team, here are the notes from today…</p>
	HtmlBody *string `json:"htmlBody,omitempty"`

	// ReplyAll When true, replies to everyone: the other participants of the original (its To and Cc, minus yourself and anyone already in To) are added to Cc.
	//
	// Example: false
	ReplyAll *bool `json:"replyAll,omitempty"`

	// Subject Subject of the reply. Optional — when omitted, a `Re:`-prefixed subject is derived from the original email.
	//
	// Example: Re: Weekly sync notes
	Subject *string `json:"subject,omitempty"`

	// TextBody Plain-text version of the email body
	//
	// Example: Hi team, here are the notes from today…
	TextBody *string `json:"textBody,omitempty"`

	// To Recipients. Optional — when omitted, derived from the original message's sender (its Reply-To, falling back to From). When given, used as-is, e.g. after the caller edited the pre-filled recipient.
	To *[]EmailAddressDto `json:"to,omitempty"`
}

// ReplyEmailRequestDtoDeliveryMode Example: INTERNXT
type ReplyEmailRequestDtoDeliveryMode string

// SearchEmailQueryDto defines model for SearchEmailQueryDto.
type SearchEmailQueryDto struct {
	// After ISO 8601 date — emails received after this date
	After *string `json:"after,omitempty"`

	// Before ISO 8601 date — emails received before this date
	Before *string `json:"before,omitempty"`

	// From Filter by sender
	//
	// Example: ["a@inxt.eu","b@inxt.me"]
	From *[]string `json:"from,omitempty"`

	// HasAttachment Filter by attachment presence
	HasAttachment *bool `json:"hasAttachment,omitempty"`

	// Limit Example: 20
	Limit *float32 `json:"limit,omitempty"`

	// Position Example: 0
	Position *float32 `json:"position,omitempty"`

	// Text Full-text search
	Text *string `json:"text,omitempty"`

	// To Filter by recipient
	//
	// Example: ["a@inxt.eu","b@inxt.me"]
	To *[]string `json:"to,omitempty"`

	// Unread Filter by read status
	Unread *bool `json:"unread,omitempty"`
}

// SendEmailRequestDto defines model for SendEmailRequestDto.
type SendEmailRequestDto struct {
	Attachments *[]AttachmentRefDto `json:"attachments,omitempty"`
	Bcc         *[]EmailAddressDto  `json:"bcc,omitempty"`
	Cc          *[]EmailAddressDto  `json:"cc,omitempty"`

	// DeliveryMode Example: INTERNXT
	DeliveryMode *SendEmailRequestDtoDeliveryMode `json:"deliveryMode,omitempty"`

	// DraftId JMAP id of the draft being sent. When present, the draft is destroyed after the email is sent so it no longer appears in the Drafts folder.
	//
	// Example: Ma1f09b…
	DraftId    *string             `json:"draftId,omitempty"`
	Encryption *EncryptionBlockDto `json:"encryption,omitempty"`

	// HtmlBody HTML version of the email body
	//
	// Example: <p>Hi team, here are the notes from today…</p>
	HtmlBody *string `json:"htmlBody,omitempty"`

	// InReplyToEmailId JMAP id of the email being replied to (for threading)
	//
	// Example: Ma1f09b…
	InReplyToEmailId *string `json:"inReplyToEmailId,omitempty"`

	// Subject Example: Weekly sync notes
	Subject string `json:"subject"`

	// TextBody Plain-text version of the email body
	//
	// Example: Hi team, here are the notes from today…
	TextBody *string `json:"textBody,omitempty"`

	// To Primary recipients (at least one required)
	To []EmailAddressDto `json:"to"`
}

// SendEmailRequestDtoDeliveryMode Example: INTERNXT
type SendEmailRequestDtoDeliveryMode string

// UpdateEmailRequestDto defines model for UpdateEmailRequestDto.
type UpdateEmailRequestDto struct {
	// IsFlagged Flag or unflag the email
	//
	// Example: false
	IsFlagged *bool `json:"isFlagged,omitempty"`

	// IsRead Mark the email as read or unread
	//
	// Example: true
	IsRead *bool `json:"isRead,omitempty"`

	// Mailbox Move the email to this mailbox
	//
	// Example: trash
	Mailbox *UpdateEmailRequestDtoMailbox `json:"mailbox,omitempty"`
}

// UpdateEmailRequestDtoMailbox Move the email to this mailbox
//
// Example: trash
type UpdateEmailRequestDtoMailbox string

// UploadAttachmentResponseDto defines model for UploadAttachmentResponseDto.
type UploadAttachmentResponseDto struct {
	// BlobId Example: T1a2b3c…
	BlobId string `json:"blobId"`

	// Name Example: photo.jpg
	Name string `json:"name"`

	// Size Size in bytes
	//
	// Example: 4096
	Size float32 `json:"size"`

	// Type Example: image/jpeg
	Type string `json:"type"`
}

// AddressesControllerCheckAvailabilityParams defines parameters for AddressesControllerCheckAvailability.
type AddressesControllerCheckAvailabilityParams struct {
	// Username Local part of the email address (before the @)
	Username string `form:"username" json:"username"`

	// Domain Email domain
	Domain string `form:"domain" json:"domain"`
}

// EmailControllerListParams defines parameters for EmailControllerList.
type EmailControllerListParams struct {
	// Mailbox Mailbox to filter by. Omit to list emails from all mailboxes.
	Mailbox *EmailControllerListParamsMailbox `form:"mailbox,omitempty" json:"mailbox,omitempty"`

	// Limit Maximum number of emails to return. Defaults to `20`.
	Limit *float32 `form:"limit,omitempty" json:"limit,omitempty"`

	// Position Zero-based offset for pagination. Defaults to `0`.
	Position *float32 `form:"position,omitempty" json:"position,omitempty"`

	// AnchorId Anchor ID for pagination.
	AnchorId *string `form:"anchorId,omitempty" json:"anchorId,omitempty"`

	// Unread Filter by read status.
	Unread *bool `form:"unread,omitempty" json:"unread,omitempty"`
}

// EmailControllerListParamsMailbox defines parameters for EmailControllerList.
type EmailControllerListParamsMailbox string

// EmailControllerDownloadAttachmentParams defines parameters for EmailControllerDownloadAttachment.
type EmailControllerDownloadAttachmentParams struct {
	Type interface{} `form:"type,omitempty" json:"type,omitempty"`
	Name interface{} `form:"name,omitempty" json:"name,omitempty"`
}

// UserControllerGetMailAccountKeysParams defines parameters for UserControllerGetMailAccountKeys.
type UserControllerGetMailAccountKeysParams struct {
	// Address Address whose keys to fetch. Defaults to the caller`s primary address.
	Address *string `form:"address,omitempty" json:"address,omitempty"`
}

// EmailControllerSaveDraftJSONRequestBody defines body for EmailControllerSaveDraft for application/json ContentType.
type EmailControllerSaveDraftJSONRequestBody = DraftEmailRequestDto

// EmailControllerUpdateDraftJSONRequestBody defines body for EmailControllerUpdateDraft for application/json ContentType.
type EmailControllerUpdateDraftJSONRequestBody = DraftEmailRequestDto

// EmailControllerLookupRecipientKeysJSONRequestBody defines body for EmailControllerLookupRecipientKeys for application/json ContentType.
type EmailControllerLookupRecipientKeysJSONRequestBody = LookupRecipientKeysRequestDto

// EmailControllerSearchJSONRequestBody defines body for EmailControllerSearch for application/json ContentType.
type EmailControllerSearchJSONRequestBody = SearchEmailQueryDto

// EmailControllerSendJSONRequestBody defines body for EmailControllerSend for application/json ContentType.
type EmailControllerSendJSONRequestBody = SendEmailRequestDto

// EmailControllerUpdateJSONRequestBody defines body for EmailControllerUpdate for application/json ContentType.
type EmailControllerUpdateJSONRequestBody = UpdateEmailRequestDto

// EmailControllerReplyJSONRequestBody defines body for EmailControllerReply for application/json ContentType.
type EmailControllerReplyJSONRequestBody = ReplyEmailRequestDto

// UserControllerCreateMailAccountJSONRequestBody defines body for UserControllerCreateMailAccount for application/json ContentType.
type UserControllerCreateMailAccountJSONRequestBody = CreateMailAccountDto
